name: Trigger Local Env

on:
  push:
    branches:
      - test

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/Yam1x/to-dos-local-env/dispatches \
          -d '{"event_type": "trigger_from_UI"}' 

          
      - name: Wait for Local Env tests to pass
        run: |
          curl -s -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
          https://api.github.com/repos/Yam1x/to-dos-local-env/actions/runs

