name: Trigger Local Env

on:
  push:
    branches:
      - test

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/Yam1x/to-dos-local-env/dispatches \
          -d '{"event_type": "trigger_from_UI"}' 

          
      - name: Wait for Local Env tests to pass
        run: |
          while true; do
            STATUS=$(curl -s -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            https://api.github.com/repos/Yam1x/to-dos-local-env/actions/runs \
            | jq '.workflow_runs | map(select(.head_branch == "master")) | .[-1] | .status')

            echo "$STATUS"

            if [ "$STATUS" == "\"success\"" ]; then
              echo "Tests passed"
              exit 0
            elif [ "$STATUS" == "\"failure\"" ]; then
              echo "Tests failed"
              exit 1
            fi

            echo "Waiting for test results..."
            sleep 30
          done
